### ISSUE TITLE
Torch make people kick

### ISSUE THREAD

**Issue by GoodLucky777** [Creeperface01/GAC#6]
GAC detect hack when I just break torch(a block that can be break easily).

**Comment by GoodLucky777** [comment]
Or like Leaf blocks

**Comment by Creeperface01** [comment]
GAC uses nukkit values for this. So it must be wrong in nukkit

**Comment by Creeperface01** [comment]
and does it happen always or how often?

**Comment by GoodLucky777** [comment]
It says nuker detected

**Comment by GoodLucky777** [comment]
It often happen

**Comment by Creeperface01** [comment]
Ah it's something else. Disable nuker check for now

**Comment by GoodLucky777** [comment]
so.. are you going to fix a nuker?

**Comment by GoodLucky777** [comment]
it works well when i disable nuker

**Comment by Creeperface01** [comment]
I fixed it somewhere already but need to find it where 😅

**Comment by Creeperface01** [comment]
seems to be fixed
